image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-master:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master
  tags:
    - docker

build-develop:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE-importer:$CI_COMMIT_REF_SLUG" -f Dockerfile-py .
    - docker push "$CI_REGISTRY_IMAGE-importer:$CI_COMMIT_REF_SLUG"
    - docker build --pull -t "$CI_REGISTRY_IMAGE-dashboard:$CI_COMMIT_REF_SLUG" -f Dockerfile-r .
    - docker push "$CI_REGISTRY_IMAGE-dashboard:$CI_COMMIT_REF_SLUG"
  only:
    - develop
  tags:
    - docker

build-tag:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  only:
    - tags
  tags:
    - docker
