FROM python:3

COPY Python/requirements.txt requirements.txt
COPY Python/ scripts/

RUN pip install --upgrade pip && pip install -r requirements.txt

ENTRYPOINT ["python", "/scripts/scraping.py"]