---
title: "Changes"
author: "Jens Laufer"
date: "18 11 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F, warning = F)
```

```{r}
library(bbplot)
```


```{r}
source("../apps/api.R")
source("../apps/visualisations.R")
windowsFonts(Helvetica = "TT Arial")
```

```{r}
data <- load.data()
```




```{r fig.height=10, fig.width=20}

source("../apps/visualisations.R")
data %>% 
  #filter(Gravity_Change <0.0010 & Gravity_Change >-0.001) %>%
  filter(Gravity_Change < .2 & Gravity_Change > 0.19) %>% 
  plot.gravity.change.barchart()
```

```{r}

source("../apps/visualisations.R")
data %>% 
  filter(!is.na(ParentCategory)) %>% 
  group_by(Id, Title,Gravity, ActivateDate) %>% 
  dplyr::summarise(Gravity_Change_mean=median(Gravity_Change, na.rm = T)) %>% 
  filter(Gravity > 5 & !is.infinite(Gravity_Change_mean) & Gravity_Change_mean>0.01) %>% 
  arrange(-Gravity,-Gravity_Change_mean) 
  
```



```{r fig.height=10, fig.width=20}

  data %>%
  filter(!is.na(ParentCategory)) %>% 
  plot.gravity.change.history( "BLOODSUG")
```


```{r fig.height=10, fig.width=20}

source("../apps/visualisations.R")
data %>%
  filter(is.na(ParentCategory)) %>% 
  plot.gravity.change.history("EASIEST123")
```

```{r fig.height=10, fig.width=20}

source("../apps/visualisations.R")
data %>% plot.gravity.gravity.change
```



```{r}

data %>%  
  arrange(-Gravity_Change_mean) %>% 
  distinct(Id, .keep_all = T) %>% 
  select(Id, Gravity_Change_mean) %>%
  filter(!is.infinite(Gravity_Change_mean)) %>% 
  arrange(-Gravity_Change_mean) 
```

```{r}
data %>% 
  filter(is.na(ParentCategory) & Id == "007XHTML") %>% 
  select(Id, Date, Gravity, Gravity_Change, Gravity_Change_mean)
```


```{r fig.height=10, fig.width=20}

source("../apps/visualisations.R")
data %>%
  filter(is.na(ParentCategory)) %>% 
  plot.gravity.change.history("TRUST2021")
```


